Algoritmo "notapositivanegativa"
// Disciplina  :  [Algoritmia]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2017
Var
// Seção de Declarações das variáveis 
 noTa:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  leia(nota)
  se(nota>-10) entao
  escreva("positiva")
  senao
  escreva("negativa")
  fimse
Fimalgoritmo